include:
  # lily58
  - board: seeeduino_xiao_ble
    shield: lily58_dongle
    artifact-name: lily58_dongle
  - board: nice_nano_v2
    shield: lily58_left
    artifact-name: lily58_central_left
  - board: nice_nano_v2
    shield: lily58_left
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: lily58_peripheral_left
  - board: nice_nano_v2
    shield: lily58_right
    artifact-name: lily58_peripheral_right

  # reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
  - board: nice_nano_v2
    shield: settings_reset
