name: Build ZMK firmware
on:
  workflow_dispatch:
  pull_request:
  push:
    paths:
      - "config/keymap/**"
      - "config/*.conf"
      - "config/*.keymap"
      - "boards/**"
      - "build.yaml"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
    with:
      archive_name: ${{ github.repository_owner }}-zmk-config-${{ github.sha }}-${{ github.run_number }}
